version: "3.9"

services:
  web:
    container_name: web
    build: ./backend
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - django_static_volume/:/usr/src/app/static
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  react:
    container_name: react
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - react_static_volume:/usr/src/app/build/static
    expose:
      - 3000
    env_file:
      - ./.env.dev
    command: serve -s build -l 3000
    depends_on:
      - web

  db:
    container_name: db
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "6543:5432"

  tensorflow-servings:
    container_name: tfserving_classifier
    build: ./algorithms
    ports:
      - 8501:8501
    depends_on:
      - web

  redis:
    container_name: redis
    image: "redis:alpine"

  celery:
    container_name: celery
    build:
      context: ./backend
    command: celery -A server worker -l INFO
    volumes:
      - ./backend/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - db
      - web

  flower:
    container_name: flower
    build: ./backend
    command: celery flower worker -l INFO
    ports:
      - 5556:5555
    environment:
      - FLASK_DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - celery

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    volumes:
      - django_static_volume:/usr/src/app/django_files/static
      - react_static_volume:/usr/src/app/web_frontend/static
    ports:
      - 80:80
    depends_on:
      - react


volumes:
  postgres_data:
  react_static_volume:
  django_static_volume:
