version: "3.9"

services:
  web:
    image: "${WEB_IMAGE}"
    container_name: website
    command: bash -c "gunicorn server.wsgi:application --bind 0.0.0.0:8000 && python manage.py collectstatic"
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 8000:8000
    env_file: .env.prod

  nginx:
    image: "${NGINX_IMAGE}"
    container_name: nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

  tensorflow-servings:
    image: "${TENSORFLOW_IMAGE}"
    container_name: tensorflow_serving
    ports:
      - 8501:8501
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:


