version: "3.8"

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_HOST:$DATABASE_PORT/$DATABASE_NAME
    env_file:
      - .env

  db:
    image: postgres
    container_name: pgdb
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_PASS: $DATABASE_PASSWORD
      DATABASE_HOST: $DATABASE_HOST
      DATABASE_NAME: $DATABASE_NAME

    env_file:
      - .env

