version: "3.9"

services:

  web:
    container_name: website
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
    networks:
      - djangonetwork

  db:
    container_name: database
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=app
    networks:
      - djangonetwork
    ports:
      - "6543:5432"

  tensorflow-servings:
    container_name: tfserving_classifier
    build: ./algorithms
    ports:
      - 8501:8501
    depends_on:
      - web
    networks:
      - djangonetwork

volumes:
  postgres_data:

networks:
    djangonetwork:
        driver: bridge

