version: "3.9"

services:

  web:
    container_name: web
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "6543:5432"

  tensorflow-servings:
    container_name: tfserving_classifier
    build: ./algorithms
    ports:
      - 8501:8501
    depends_on:
      - web

  redis:
    container_name: redis
    image: "redis:alpine"

  celery:
    container_name: celery
    build:
      context: ./backend
    command: celery -A server worker -l INFO
    volumes:
      - ./backend/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - db
      - web

  flower:
    container_name: flower
    build: ./backend
    command: celery flower worker -l INFO
    ports:
      - 5556:5555
    environment:
      - FLASK_DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - celery

volumes:
  postgres_data:
